[GH] Fix broken `teardown` job in `integration_tests.yml` workflow
## Proposed Changes

Add missing `$` character when setting the result variable in the `workflow-status` step.
This bug is the main reason for all these failures: https://github.com/androidx/androidx/actions/workflows/integration_tests.yml

## Testing

Test: Run the new workflow and check that the following error is no longer present:

```
Error: Unable to deliver Web Hook SyntaxError: Unexpected token ',', ..."success": , "src" : "... is not valid JSON
```

This is an imported pull request from https://github.com/androidx/androidx/pull/790.

Resolves #790
Github-Pr-Head-Sha: e723d94c9dd4861c23619fea1cc7bdc51e71540b
GitOrigin-RevId: 6d2c5d66044047c789e27dede6f7ace5e09b4659
Change-Id: Ieac61ec0b6659124ef40742e674cff92d5e2af88