Revert "Configure kotlin multiplatform build in the navigation-common."
This reverts commit c941df78c831fa40a5208ab162e5925df0d92085.

Reason for revert: Post submit failing due to:

Execution failed for task ':navigation:navigation-common:generateMetadataFileForLinuxX64Publication'.
> java.io.FileNotFoundException: $OUT_DIR/androidx/navigation/navigation-common/build/libs/navigation-common-linuxX64Main-2.9.0-alpha04.klib (No such file or directory)

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':navigation:navigation-common:generateMetadataFileForLinuxX64Publication'.
Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: $OUT_DIR/androidx/navigation/navigation-common/build/libs/navigation-common-linuxX64Main-2.9.0-alpha04.klib (No such file or directory)
Caused by: java.io.FileNotFoundException: $OUT_DIR/androidx/navigation/navigation-common/build/libs/navigation-common-linuxX64Main-2.9.0-alpha04.klib (No such file or directory)

Change-Id: I6d8ab11f3298531eb3a5b229fd71d6c9e79a21a3